version: 2.1

orbs: 
  browser-tools: circleci/browser-tools@1.3.0

jobs:
  test:
    docker:
      - image: cimg/node:16.13-browsers
    steps:
      - browser-tools/install-chrome
      - run: |
          node --version
          java --version
          google-chrome --version
      - run: |
          which google-chrome
          ls -laH /usr/bin/google-chrome

workflows:
  main:
    jobs:
      - test
