version: 2.1

orbs: 
  browser-tools: circleci/browser-tools@1.3.0

jobs:
  test:
    docker:
      - image: cimg/node:16.13-browsers
    steps:
      - browser-tools/install-chrome
      - run: |
          node --version
          java --version
          google-chrome --version
      - run: |
          which google-chrome
          ls -laH /usr/bin/google-chrome
      - run:
          name: launch Xvfb
          command: |
            sudo apt-get -y update
            sudo apt-get install -y x11-utils
            
            launch_xvfb() {
                # Set defaults if the user did not specify envs.
                export DISPLAY=${XVFB_DISPLAY:-:1}
                local screen=${XVFB_SCREEN:-0}
                local resolution=${XVFB_RESOLUTION:-1280x1024x24}
                local timeout=${XVFB_TIMEOUT:-5}
                # Start and wait for either Xvfb to be fully up,
                # or we hit the timeout.
                Xvfb ${DISPLAY} -screen ${screen} ${resolution} &
                local loopCount=0
                until xdpyinfo -display ${DISPLAY} > /dev/null 2>&1
                do
                    loopCount=$((loopCount+1))
                    sleep 1
                    if [ ${loopCount} -gt ${timeout} ]
                    then
                        echo "[ERROR] xvfb failed to start."
                        exit 1
                    fi
                done
            }
            
            launch_xvfb
            echo "Launced Xvfb"

workflows:
  main:
    jobs:
      - test
